/**
 * category : plan(시딩박스 / 기획패키지) | savary(싸바리) | dan(단상자) | shop(쇼핑백) | print(인쇄물) | custom(커스텀)
 * isSlide(boolean) : 메인페이지 포트폴리오 섹션 슬라이더 포함 여부
 * infos > topic : 품명, 형태, 지종, 인쇄, 코팅, 후가공, 원단, 부자재
 */

export const portfolioData = [
    {
        seq: 'db_001',
        name: 'TirrLirr x AROMATICA',
        category: ['plan', 'savary'],
        isSlide: true,
        slideList: [{ url: '/assets/image/portfolio/db_001/img1.png' }, { url: '/assets/image/portfolio/db_001/img2.png' }, { url: '/assets/image/portfolio/db_001/img3.png' }, { url: '/assets/image/portfolio/db_001/img5.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_001/thum1.png' }, { url: '/assets/image/portfolio/db_001/thum2.png' }],
        imgList: [{ url: '/assets/image/portfolio/db_001/img1.png', width: 2109, height: 2235 }, { url: '/assets/image/portfolio/db_001/img2.png', width: 2400, height: 2128 }, { url: '/assets/image/portfolio/db_001/img3.png', width: 1801, height: 2400 }, { url: '/assets/image/portfolio/db_001/img4.png', width: 1800, height: 2400 }, , { url: '/assets/image/portfolio/db_001/img5.png', width: 1799, height: 2400 }],
        infos: [
            { topic: '품명', info: '티르리르 x 아로마티카 - 연말 콜라보 패키지' },
            { topic: '형태', info: '표지+지함 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '원색 2도 + 별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
        ],
    },
    {
        seq: 'db_002',
        name: 'OLENS 연말 기프트 패키지',
        category: ['savary', 'plan'],
        isSlide: false,
        slideList: [{ url: '/assets/image/portfolio/db_002/img1.png' }, { url: '/assets/image/portfolio/db_002/img5.png' }, { url: '/assets/image/portfolio/db_002/img3.png' }, { url: '/assets/image/portfolio/db_002/img4.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_002/thum1.png' }, { url: '/assets/image/portfolio/db_002/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_002/img1.png', width: 2400, height: 1349 },
            { url: '/assets/image/portfolio/db_002/img2.png', width: 2400, height: 1797 },
            { url: '/assets/image/portfolio/db_002/img3.png', width: 2400, height: 1349 },
            { url: '/assets/image/portfolio/db_002/img4.png', width: 2022, height: 1536 },
            { url: '/assets/image/portfolio/db_002/img5.png', width: 2400, height: 1349 },
            { url: '/assets/image/portfolio/db_002/img6.png', width: 2400, height: 1349 },
        ],
        infos: [
            { topic: '품명', info: 'OLENS - 렌즈 연말 기프트 패키지' },
            { topic: '형태', info: '커스텀 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '원색 2도 + 별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
        ],
    },
    {
        seq: 'db_003',
        name: 'CARIN 안경 패키지',
        category: ['savary'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_003/thum1.png' }, { url: '/assets/image/portfolio/db_003/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_003/img1.png', width: 1767, height: 2400 },
            { url: '/assets/image/portfolio/db_003/img2.png', width: 1856, height: 2400 },
            { url: '/assets/image/portfolio/db_003/img3.png', width: 1800, height: 2400 },
            { url: '/assets/image/portfolio/db_003/img4.png', width: 1800, height: 2400 },
            { url: '/assets/image/portfolio/db_003/img5.png', width: 2400, height: 2018 },
            { url: '/assets/image/portfolio/db_003/img6.png', width: 1799, height: 2400 },
            { url: '/assets/image/portfolio/db_003/img7.png', width: 1801, height: 2400 },
        ],
        infos: [
            { topic: '품명', info: 'CARIN - 카린 안경 패키지' },
            { topic: '형태', info: '서랍형 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '원색 2도 + 별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
        ],
    },
    {
        seq: 'db_004',
        name: 'CARIN 기프트 패키지',
        category: ['savary'],
        isSlide: false,
        slideList: [{ url: '/assets/image/portfolio/db_004/img1.png' }, { url: '/assets/image/portfolio/db_004/img2.png' }, { url: '/assets/image/portfolio/db_004/img3.png' }, { url: '/assets/image/portfolio/db_004/img4.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_004/thum1.png' }, { url: '/assets/image/portfolio/db_004/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_004/img1.png', width: 2400, height: 1871 },
            { url: '/assets/image/portfolio/db_004/img2.png', width: 1874, height: 2400 },
            { url: '/assets/image/portfolio/db_004/img3.png', width: 1799, height: 2400 },
            { url: '/assets/image/portfolio/db_004/img4.png', width: 2153, height: 2400 },
            { url: '/assets/image/portfolio/db_004/img5.png', width: 1800, height: 2400 },
            { url: '/assets/image/portfolio/db_004/img6.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: 'CARIN - 카린 안경 기프트 패키지' },
            { topic: '형태', info: '표지+지함 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '원색 2도 + 별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
        ],
    },
    {
        seq: 'db_005',
        name: 'CARIN 택배 패키지',
        category: ['dan'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_005/thum1.png' }, { url: '/assets/image/portfolio/db_005/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_005/img1.png', width: 1800, height: 2400 },
            { url: '/assets/image/portfolio/db_005/img2.png', width: 1800, height: 2400 },
            { url: '/assets/image/portfolio/db_005/img3.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_005/img4.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_005/img5.png', width: 1801, height: 2400 },
            { url: '/assets/image/portfolio/db_005/img6.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: 'CARIN - 카린 중국몰 택배박스' },
            { topic: '형태', info: 'G형 단상자' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_006',
        name: 'STAND OIL x HUH YUNJIN',
        category: ['plan', 'savary'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_006/thum1.png' }, { url: '/assets/image/portfolio/db_006/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_006/img1.png', width: 2400, height: 1500 },
            { url: '/assets/image/portfolio/db_006/img2.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_006/img3.png', width: 1920, height: 2400 },
            { url: '/assets/image/portfolio/db_006/img4.png', width: 2400, height: 1500 },
            { url: '/assets/image/portfolio/db_006/img5.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_006/img6.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: 'STAND OIL - 스탠드오일 SO BREEZY x HUH YUNJIN 콜라보 패키지' },
            { topic: '형태', info: '커스텀 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
        ],
    },
    {
        seq: 'db_007',
        name: 'SEOLPPEU x CARIN',
        category: ['plan', 'dan'],
        isSlide: false,
        slideList: [{ url: '/assets/image/portfolio/db_007/img1.png' }, { url: '/assets/image/portfolio/db_007/img2.png' }, { url: '/assets/image/portfolio/db_007/img3.png' }, { url: '/assets/image/portfolio/db_007/img4.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_007/thum1.png' }, { url: '/assets/image/portfolio/db_007/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_007/img1.png', width: 1802, height: 2400 },
            { url: '/assets/image/portfolio/db_007/img2.png', width: 2400, height: 1349 },
            { url: '/assets/image/portfolio/db_007/img3.png', width: 2400, height: 1500 },
            { url: '/assets/image/portfolio/db_007/img4.png', width: 2400, height: 2400 },
        ],
        infos: [
            { topic: '품명', info: 'CARIN - SEOLPPEU x CARIN 선글라스 패키지' },
            { topic: '형태', info: 'Y형 슬리브 단상자' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
            { topic: '부자재', info: 'pet' },
        ],
    },
    {
        seq: 'db_008',
        name: 'OLENS x Jooshica',
        category: ['plan', 'savary'],
        isSlide: false,
        slideList: [{ url: '/assets/image/portfolio/db_007/img1.png' }, { url: '/assets/image/portfolio/db_007/img2.png' }, { url: '/assets/image/portfolio/db_007/img3.png' }, { url: '/assets/image/portfolio/db_007/img4.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_008/thum1.png' }, { url: '/assets/image/portfolio/db_008/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_008/img1.png', width: 2400, height: 2400 },
            { url: '/assets/image/portfolio/db_008/img2.png', width: 2400, height: 2400 },
            { url: '/assets/image/portfolio/db_008/img3.png', width: 2400, height: 1799 },
            { url: '/assets/image/portfolio/db_008/img4.png', width: 2400, height: 2400 },
            { url: '/assets/image/portfolio/db_008/img5.png', width: 2400, height: 1348 },
            { url: '/assets/image/portfolio/db_008/img6.png', width: 2400, height: 1349 },
        ],
        infos: [
            { topic: '품명', info: 'OLENS - OLENS x Jooshica 시딩 패키지' },
            { topic: '형태', info: '표지+지함 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
        ],
    },
    {
        seq: 'db_009',
        name: 'OLENS x CLIO',
        category: ['plan', 'savary'],
        isSlide: false,
        slideList: [{ url: '/assets/image/portfolio/db_009/img1.png' }, { url: '/assets/image/portfolio/db_009/img3.png' }, { url: '/assets/image/portfolio/db_009/img5.png' }, { url: '/assets/image/portfolio/db_009/img6.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_009/thum1.png' }, { url: '/assets/image/portfolio/db_009/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_009/img1.png', width: 1799, height: 2400 },
            { url: '/assets/image/portfolio/db_009/img2.png', width: 2400, height: 1349 },
            { url: '/assets/image/portfolio/db_009/img3.png', width: 2400, height: 2400 },
            { url: '/assets/image/portfolio/db_009/img4.png', width: 2400, height: 2400 },
            { url: '/assets/image/portfolio/db_009/img5.png', width: 2400, height: 1919 },
            { url: '/assets/image/portfolio/db_009/img6.png', width: 1598, height: 2400 },
        ],
        infos: [
            { topic: '품명', info: 'OLENS - OLENS x CLIO 콜라보 시딩패키지' },
            { topic: '형태', info: '커스텀 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
        ],
    },
    {
        seq: 'db_010',
        name: 'CARIN 25FALL 컬렉션 카드',
        category: ['print'],
        isSlide: false,
        slideList: [{ url: '/assets/image/portfolio/db_009/img1.png' }, { url: '/assets/image/portfolio/db_009/img3.png' }, { url: '/assets/image/portfolio/db_009/img5.png' }, { url: '/assets/image/portfolio/db_009/img6.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_010/thum1.png' }, { url: '/assets/image/portfolio/db_010/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_010/img1.png', width: 2400, height: 2400 },
            { url: '/assets/image/portfolio/db_010/img2.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_010/img3.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_010/img4.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: 'CARIN - 카린 25FALL 컬렉션 카드' },
            { topic: '형태', info: '엽서카드 인쇄물' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_011',
        name: '디자인 무지 노트',
        category: ['print'],
        isSlide: false,
        slideList: [{ url: '/assets/image/portfolio/db_009/img1.png' }, { url: '/assets/image/portfolio/db_009/img3.png' }, { url: '/assets/image/portfolio/db_009/img5.png' }, { url: '/assets/image/portfolio/db_009/img6.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_011/thum1.png' }, { url: '/assets/image/portfolio/db_011/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_011/img1.png', width: 1800, height: 2400 },
            { url: '/assets/image/portfolio/db_011/img2.png', width: 1855, height: 2400 },
            { url: '/assets/image/portfolio/db_011/img3.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_011/img4.png', width: 1800, height: 2400 },
            { url: '/assets/image/portfolio/db_011/img5.png', width: 1800, height: 2400 },
            { url: '/assets/image/portfolio/db_011/img6.png', width: 1800, height: 2400 },
            { url: '/assets/image/portfolio/db_011/img7.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: '디자인 무지 노트' },
            { topic: '형태', info: '무지 노트' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_012',
        name: 'Heineken 기프트 패키지',
        category: ['savary', 'plan'],
        isSlide: true,
        slideList: [{ url: '/assets/image/portfolio/db_012/img1.png' }, { url: '/assets/image/portfolio/db_012/img7.png' }, { url: '/assets/image/portfolio/db_012/img4.png' }, { url: '/assets/image/portfolio/db_012/img3.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_012/thum1.png' }, { url: '/assets/image/portfolio/db_012/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_012/img1.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_012/img2.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_012/img3.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_012/img4.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_012/img5.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_012/img6.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_012/img7.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: '하이네켄 - 하이네켄 기프트 패키지' },
            { topic: '형태', info: '표지+지함 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_013',
        name: '케어셀 LED 마스크 패키지',
        category: ['savary'],
        isSlide: false,
        slideList: [{ url: '/assets/image/portfolio/db_012/img1.png' }, { url: '/assets/image/portfolio/db_012/img7.png' }, { url: '/assets/image/portfolio/db_012/img4.png' }, { url: '/assets/image/portfolio/db_012/img3.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_013/thum1.png' }, { url: '/assets/image/portfolio/db_013/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_013/img1.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_013/img2.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_013/img3.png', width: 2400, height: 2345 },
            { url: '/assets/image/portfolio/db_013/img4.png', width: 2400, height: 1708 },
            { url: '/assets/image/portfolio/db_013/img5.png', width: 2400, height: 1739 },
            { url: '/assets/image/portfolio/db_013/img6.png', width: 2400, height: 1984 },
        ],
        infos: [
            { topic: '품명', info: '케어셀 LED 마스크 패키지' },
            { topic: '형태', info: '표지+지함 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_014',
        name: '다산제약 유산균 패키지',
        category: ['savary'],
        isSlide: false,
        slideList: [{ url: '/assets/image/portfolio/db_012/img1.png' }, { url: '/assets/image/portfolio/db_012/img7.png' }, { url: '/assets/image/portfolio/db_012/img4.png' }, { url: '/assets/image/portfolio/db_012/img3.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_014/thum1.png' }, { url: '/assets/image/portfolio/db_014/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_014/img1.png', width: 2400, height: 1686 },
            { url: '/assets/image/portfolio/db_014/img2.png', width: 2400, height: 1828 },
            { url: '/assets/image/portfolio/db_014/img3.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_014/img4.png', width: 2400, height: 1660 },
            { url: '/assets/image/portfolio/db_014/img5.png', width: 2400, height: 1668 },
        ],
        infos: [
            { topic: '품명', info: '다산제약 - 다산제약 유산균 패키지' },
            { topic: '형태', info: '표지+지함 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_015',
        name: 'DESPERADOS 기프트 패키지',
        category: ['savary'],
        isSlide: true,
        slideList: [{ url: '/assets/image/portfolio/db_015/img1.png' }, { url: '/assets/image/portfolio/db_015/img3.png' }, { url: '/assets/image/portfolio/db_015/img6.png' }, { url: '/assets/image/portfolio/db_015/img4.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_015/thum1.png' }, { url: '/assets/image/portfolio/db_015/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_015/img1.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_015/img2.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_015/img3.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_015/img4.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_015/img5.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_015/img6.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: 'DESPERADOS - 데스페라도스 맥주 기프트 패키지' },
            { topic: '형태', info: '표지+지함 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_016',
        name: '영양제 서랍형 싸바리 박스',
        category: ['savary'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_016/thum1.png' }, { url: '/assets/image/portfolio/db_016/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_016/img1.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_016/img2.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_016/img3.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_016/img4.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_016/img5.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: '영양제 서랍형 싸바리 박스' },
            { topic: '형태', info: '표지+지함 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_017',
        name: '영양제 3단 싸바리 박스',
        category: ['savary'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_017/thum1.png' }, { url: '/assets/image/portfolio/db_017/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_017/img1.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_017/img2.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_017/img3.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_017/img4.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_017/img5.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: '영양제 3단 싸바리 박스' },
            { topic: '형태', info: '3단 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_018',
        name: '식스엘 프로바이오틱스 패키지',
        category: ['savary'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_018/thum1.png' }, { url: '/assets/image/portfolio/db_018/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_018/img1.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_018/img2.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_018/img3.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_018/img4.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_018/img5.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_018/img6.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: '식스엘 프로바이오틱스 패키지' },
            { topic: '형태', info: '표지+지함 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_019',
        name: '포스파민 영양제 패키지',
        category: ['savary'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_019/thum1.png' }, { url: '/assets/image/portfolio/db_019/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_019/img1.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_019/img2.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_019/img3.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_019/img4.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_019/img5.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_019/img6.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: '포스파민 영양제 패키지' },
            { topic: '형태', info: '표지+지함 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_020',
        name: '원기 상황버섯 패키지',
        category: ['plan'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_020/thum1.png' }, { url: '/assets/image/portfolio/db_020/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_020/img1.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_020/img2.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_020/img3.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_020/img4.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_020/img5.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: '원기 상황버섯 패키지' },
            { topic: '형태', info: '커스텀 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_021',
        name: '리덴탈 잇몸 영양제 패키지',
        category: ['plan'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_021/thum1.png' }, { url: '/assets/image/portfolio/db_021/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_021/img1.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_021/img2.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_021/img3.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_021/img4.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: '리덴탈 잇몸 영양제 패키지' },
            { topic: '형태', info: '2단 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_022',
        name: '조니워커 블루라벨 패키지',
        category: ['plan'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_022/thum1.png' }, { url: '/assets/image/portfolio/db_022/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_022/img1.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_022/img2.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_022/img3.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_022/img4.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_022/img5.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: '조니워커  - 조니워커 블루라벨 패키지' },
            { topic: '형태', info: '커스텀 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_023',
        name: '오렌즈 연말 쇼핑백',
        category: ['shop'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_023/thum1.png' }, { url: '/assets/image/portfolio/db_023/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_023/img1.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_023/img2.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_023/img3.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_023/img4.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: '오렌즈 - 오렌즈 연말 쇼핑백' },
            { topic: '형태', info: '매립형 쇼핑백' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_024',
        name: '오렌즈 기프트 쇼핑백',
        category: ['shop'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_024/thum1.png' }, { url: '/assets/image/portfolio/db_024/thum2.png' }],
        imgList: [{ url: '/assets/image/portfolio/db_024/img1.png', width: 2400, height: 1800 }, { url: '/assets/image/portfolio/db_024/img2.png', width: 2400, height: 1800 }, { url: '/assets/image/portfolio/db_024/img3.png', width: 2400, height: 1800 }, { url: '/assets/image/portfolio/db_024/img4.png' }],
        infos: [
            { topic: '품명', info: '오렌즈 - 오렌즈 기프트 쇼핑백' },
            { topic: '형태', info: '매립형 쇼핑백' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_025',
        name: '오렌즈 샘플 패키지',
        category: ['shop'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_025/thum1.png' }, { url: '/assets/image/portfolio/db_025/thum2.png' }],
        imgList: [
            { url: '/assets/image/portfolio/db_025/img1.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_025/img2.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_025/img3.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_025/img4.png', width: 2400, height: 1800 },
            { url: '/assets/image/portfolio/db_025/img5.png', width: 2400, height: 1800 },
        ],
        infos: [
            { topic: '품명', info: '오렌즈 - 오렌즈 샘플 패키지' },
            { topic: '형태', info: '단상자' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
];
