/**
 * category : plan(시딩박스 / 기획패키지) | savary(싸바리) | dan(단상자) | shop(쇼핑백) | print(인쇄물) | custom(커스텀)
 * isSlide(boolean) : 메인페이지 포트폴리오 섹션 슬라이더 포함 여부
 * infos > topic : 품명, 형태, 지종, 인쇄, 코팅, 후가공, 원단, 부자재
 */

export const portfolioData = [
    {
        seq: 'db_001',
        name: 'TirrLirr x AROMATICA',
        category: ['plan', 'savary'],
        isSlide: true,
        slideList: [{ url: '/assets/image/portfolio/db_001/img1.png' }, { url: '/assets/image/portfolio/db_001/img2.png' }, { url: '/assets/image/portfolio/db_001/img3.png' }, { url: '/assets/image/portfolio/db_001/img5.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_001/thum1.png' }, { url: '/assets/image/portfolio/db_001/thum2.png' }],
        imgList: [{ url: '/assets/image/portfolio/db_001/img1.png' }, { url: '/assets/image/portfolio/db_001/img2.png' }, { url: '/assets/image/portfolio/db_001/img3.png' }, { url: '/assets/image/portfolio/db_001/img4.png' }, , { url: '/assets/image/portfolio/db_001/img5.png' }],
        infos: [
            { topic: '품명', info: '티르리르 x 아로마티카 - 연말 콜라보 패키지' },
            { topic: '형태', info: '표지+지함 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '원색 2도 + 별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
        ],
    },
    {
        seq: 'db_002',
        name: 'OLENS 연말 기프트 패키지',
        category: ['savary', 'plan'],
        isSlide: true,
        slideList: [{ url: '/assets/image/portfolio/db_002/img1.png' }, { url: '/assets/image/portfolio/db_002/img5.png' }, { url: '/assets/image/portfolio/db_002/img3.png' }, { url: '/assets/image/portfolio/db_002/img4.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_002/thum1.png' }, { url: '/assets/image/portfolio/db_002/thum2.png' }],
        imgList: [{ url: '/assets/image/portfolio/db_002/img1.png' }, { url: '/assets/image/portfolio/db_002/img2.png' }, { url: '/assets/image/portfolio/db_002/img3.png' }, { url: '/assets/image/portfolio/db_002/img4.png' }, { url: '/assets/image/portfolio/db_002/img5.png' }, { url: '/assets/image/portfolio/db_002/img6.png' }],
        infos: [
            { topic: '품명', info: 'OLENS - 렌즈 연말 기프트 패키지' },
            { topic: '형태', info: '커스텀 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '원색 2도 + 별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
        ],
    },
    {
        seq: 'db_003',
        name: 'CARIN 안경 패키지',
        category: ['savary'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_003/thum1.png' }, { url: '/assets/image/portfolio/db_003/thum2.png' }],
        imgList: [{ url: '/assets/image/portfolio/db_003/img1.png' }, { url: '/assets/image/portfolio/db_003/img2.png' }, { url: '/assets/image/portfolio/db_003/img3.png' }, { url: '/assets/image/portfolio/db_003/img4.png' }, { url: '/assets/image/portfolio/db_003/img5.png' }, { url: '/assets/image/portfolio/db_003/img6.png' }, { url: '/assets/image/portfolio/db_003/img7.png' }],
        infos: [
            { topic: '품명', info: 'CARIN - 카린 안경 패키지' },
            { topic: '형태', info: '서랍형 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '원색 2도 + 별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
        ],
    },
    {
        seq: 'db_004',
        name: 'CARIN 기프트 패키지',
        category: ['savary'],
        isSlide: true,
        slideList: [{ url: '/assets/image/portfolio/db_004/img1.png' }, { url: '/assets/image/portfolio/db_004/img2.png' }, { url: '/assets/image/portfolio/db_004/img3.png' }, { url: '/assets/image/portfolio/db_004/img4.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_004/thum1.png' }, { url: '/assets/image/portfolio/db_004/thum2.png' }],
        imgList: [{ url: '/assets/image/portfolio/db_004/img1.png' }, { url: '/assets/image/portfolio/db_004/img2.png' }, { url: '/assets/image/portfolio/db_004/img3.png' }, { url: '/assets/image/portfolio/db_004/img4.png' }, { url: '/assets/image/portfolio/db_004/img5.png' }, { url: '/assets/image/portfolio/db_004/img6.png' }],
        infos: [
            { topic: '품명', info: 'CARIN - 카린 안경 기프트 패키지' },
            { topic: '형태', info: '표지+지함 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '원색 2도 + 별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
        ],
    },
    {
        seq: 'db_005',
        name: 'CARIN 택배 패키지',
        category: ['dan'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_005/thum1.png' }, { url: '/assets/image/portfolio/db_005/thum2.png' }],
        imgList: [{ url: '/assets/image/portfolio/db_005/img1.png' }, { url: '/assets/image/portfolio/db_005/img2.png' }, { url: '/assets/image/portfolio/db_005/img3.png' }, { url: '/assets/image/portfolio/db_005/img4.png' }, { url: '/assets/image/portfolio/db_005/img5.png' }, { url: '/assets/image/portfolio/db_005/img6.png' }],
        infos: [
            { topic: '품명', info: 'CARIN - 카린 중국몰 택배박스' },
            { topic: '형태', info: 'G형 단상자' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
    {
        seq: 'db_006',
        name: 'STAND OIL x HUH YUNJIN',
        category: ['plan', 'savary'],
        isSlide: false,
        thumbnailList: [{ url: '/assets/image/portfolio/db_006/thum1.png' }, { url: '/assets/image/portfolio/db_006/thum2.png' }],
        imgList: [{ url: '/assets/image/portfolio/db_006/img1.png' }, { url: '/assets/image/portfolio/db_006/img2.png' }],
        infos: [
            { topic: '품명', info: 'STAND OIL - 스탠드오일 SO BREEZY x HUH YUNJIN 콜라보 패키지' },
            { topic: '형태', info: '커스텀 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
        ],
    },
    {
        seq: 'db_007',
        name: 'SEOLPPEU x CARIN',
        category: ['plan', 'dan'],
        isSlide: true,
        slideList: [{ url: '/assets/image/portfolio/db_007/img1.png' }, { url: '/assets/image/portfolio/db_007/img2.png' }, { url: '/assets/image/portfolio/db_007/img3.png' }, { url: '/assets/image/portfolio/db_007/img4.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_007/thum1.png' }, { url: '/assets/image/portfolio/db_007/thum2.png' }],
        imgList: [{ url: '/assets/image/portfolio/db_007/img1.png' }, { url: '/assets/image/portfolio/db_007/img2.png' }, { url: '/assets/image/portfolio/db_007/img3.png' }, { url: '/assets/image/portfolio/db_007/img4.png' }],
        infos: [
            { topic: '품명', info: 'CARIN - SEOLPPEU x CARIN 선글라스 패키지' },
            { topic: '형태', info: 'Y형 슬리브 단상자' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
            { topic: '부자재', info: 'pet' },
        ],
    },
    {
        seq: 'db_008',
        name: 'OLENS x Jooshica',
        category: ['plan', 'savary'],
        isSlide: false,
        slideList: [{ url: '/assets/image/portfolio/db_007/img1.png' }, { url: '/assets/image/portfolio/db_007/img2.png' }, { url: '/assets/image/portfolio/db_007/img3.png' }, { url: '/assets/image/portfolio/db_007/img4.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_008/thum1.png' }, { url: '/assets/image/portfolio/db_008/thum2.png' }],
        imgList: [{ url: '/assets/image/portfolio/db_008/img1.png' }, { url: '/assets/image/portfolio/db_008/img2.png' }, { url: '/assets/image/portfolio/db_008/img3.png' }, { url: '/assets/image/portfolio/db_008/img4.png' }, { url: '/assets/image/portfolio/db_008/img5.png' }, { url: '/assets/image/portfolio/db_008/img6.png' }],
        infos: [
            { topic: '품명', info: 'OLENS - OLENS x Jooshica 콜라보 패키지' },
            { topic: '형태', info: '표지+지함 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
        ],
    },
    {
        seq: 'db_009',
        name: 'OLENS x CLIO',
        category: ['plan', 'savary'],
        isSlide: true,
        slideList: [{ url: '/assets/image/portfolio/db_009/img1.png' }, { url: '/assets/image/portfolio/db_009/img3.png' }, { url: '/assets/image/portfolio/db_009/img5.png' }, { url: '/assets/image/portfolio/db_009/img6.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_009/thum1.png' }, { url: '/assets/image/portfolio/db_009/thum2.png' }],
        imgList: [{ url: '/assets/image/portfolio/db_009/img1.png' }, { url: '/assets/image/portfolio/db_009/img2.png' }, { url: '/assets/image/portfolio/db_009/img3.png' }, { url: '/assets/image/portfolio/db_009/img4.png' }, { url: '/assets/image/portfolio/db_009/img5.png' }, { url: '/assets/image/portfolio/db_009/img6.png' }],
        infos: [
            { topic: '품명', info: 'OLENS - OLENS x CLIO 콜라보 시딩패키지' },
            { topic: '형태', info: '커스텀 싸바리' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
            { topic: '코팅', info: '무광 라미네이팅' },
            { topic: '후가공', info: '음각' },
        ],
    },
    {
        seq: 'db_010',
        name: 'CARIN 25FALL 컬렉션 카드',
        category: ['print'],
        isSlide: false,
        slideList: [{ url: '/assets/image/portfolio/db_009/img1.png' }, { url: '/assets/image/portfolio/db_009/img3.png' }, { url: '/assets/image/portfolio/db_009/img5.png' }, { url: '/assets/image/portfolio/db_009/img6.png' }],
        thumbnailList: [{ url: '/assets/image/portfolio/db_010/thum1.png' }, { url: '/assets/image/portfolio/db_010/thum2.png' }],
        imgList: [{ url: '/assets/image/portfolio/db_010/img1.png' }, { url: '/assets/image/portfolio/db_010/img2.png' }, { url: '/assets/image/portfolio/db_010/img3.png' }],
        infos: [
            { topic: '품명', info: 'CARIN - 카린 25FALL 컬렉션 카드' },
            { topic: '형태', info: '엽서카드 인쇄물' },
            { topic: '지종', info: '아트지 130g' },
            { topic: '인쇄', info: '별색 1도' },
        ],
    },
];
