import type { Metadata } from 'next';

import './styles/main.scss';
import Header from './components/layout/header/Header';
import Footer from './components/layout/footer/Footer';

export const metadata: Metadata = {
  title: 'Dream Box',
  description: 'Generated by chlee',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body suppressHydrationWarning>
        <Header />
        <main className="flex-1 mt-[6.9rem]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
