import type { Metadata } from 'next';

import ReactQueryClientProvider from 'root/src/app/_config/ReactQueryClientProvider';
import { Header, Footer } from 'app/_components/layout';
import './styles/main.scss';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Dream Box',
  description: 'Generated by chlee',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const KAKAO_SDK_URL = `//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAOMAP_KEY}&autoload=false`;

  return (
    <html lang="ko">
      <body suppressHydrationWarning>
        <ReactQueryClientProvider>
          <Header />
          <main className="flex-1 mt-[6.9rem]">{children}</main>
          <Footer />
        </ReactQueryClientProvider>

        <Script src={KAKAO_SDK_URL} strategy="beforeInteractive" />
      </body>
    </html>
  );
}
