import type { Metadata } from 'next';

import ReactQueryClientProvider from 'root/src/app/_provider/ReactQueryClientProvider';
import LayoutClient from './LayoutClient';
import './styles/main.scss';

export const metadata: Metadata = {
  title: 'Dream Box',
  description: 'Generated by chlee',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body suppressHydrationWarning>
        <ReactQueryClientProvider>
          <LayoutClient>{children}</LayoutClient>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
